/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Interfaces;

import Clases.Cliente;
import Clases.Transaccion;
import Clases.leerArchivo;
import java.util.Date;

/**
 *
 * @author USUARIO
 */
public class PagarCuota extends javax.swing.JDialog {
leerArchivo l=new leerArchivo("");
    /**
     * Creates new form PagarCuota
     */
    public PagarCuota(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Transaccion a=l.obtenerTransaccion();
        txtcredito.setText(a.getCredito()+"");
        txtcuota.setText(a.getCuotas()+"");
        txtdivision.setText((a.getCredito()/a.getCuotas())+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnpagar = new javax.swing.JButton();
        txtcredito = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdivision = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcuota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Credito a pagar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        btnpagar.setText("Pagar 1 CUOTA");
        btnpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagarActionPerformed(evt);
            }
        });
        getContentPane().add(btnpagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 132, 230, 40));

        txtcredito.setEditable(false);
        getContentPane().add(txtcredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 140, -1));

        jLabel2.setText("Credito/Nro.Cuota:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtdivision.setEditable(false);
        getContentPane().add(txtdivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 140, -1));

        jLabel3.setText("Nro. cuotas:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        txtcuota.setEditable(false);
        getContentPane().add(txtcuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 140, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setText("Pagar 1 Cuota");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagarActionPerformed
        Transaccion a=l.obtenerTransaccion();
        Cliente b=l.obtenerCliente1();
        double pago=Double.parseDouble(txtdivision.getText());
        double deuda=a.getCredito()-pago;
        a.setCredito(deuda);
        a.setCuotas(a.getCuotas()-1);
        l.ActualizarTransaccion(a);
        Date bb=new Date();
        l.ActualizarPagos(b.getPrenombre()+" "+b.getApellidos()+";"+a.getCuenta().getNumeroTarj()+";"+
                deuda+";"+pago+";"+bb);
        this.setVisible(false);
    }//GEN-LAST:event_btnpagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagarCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagarCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagarCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagarCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PagarCuota dialog = new PagarCuota(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtcredito;
    private javax.swing.JTextField txtcuota;
    private javax.swing.JTextField txtdivision;
    // End of variables declaration//GEN-END:variables
}
